Pig Stack Trace
---------------
ERROR 6000: 
<file ejercicio_5.pig, line 38, column 9> Output Location Validation Failed for: 'file:///home/gll/Descargas/pig/evaluacion_data/ejercicio5/join.out More info to follow:
Output directory file:/home/gll/Descargas/pig/evaluacion_data/ejercicio5/join.out already exists

org.apache.pig.impl.plan.VisitorException: ERROR 6000: 
<file ejercicio_5.pig, line 38, column 9> Output Location Validation Failed for: 'file:///home/gll/Descargas/pig/evaluacion_data/ejercicio5/join.out More info to follow:
Output directory file:/home/gll/Descargas/pig/evaluacion_data/ejercicio5/join.out already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:95)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:77)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:45)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:293)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1325)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1262)
	at org.apache.pig.PigServer.execute(PigServer.java:1254)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:366)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:133)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:194)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:166)
	at org.apache.pig.tools.grunt.Grunt.exec(Grunt.java:84)
	at org.apache.pig.Main.run(Main.java:555)
	at org.apache.pig.Main.main(Main.java:111)
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory file:/home/gll/Descargas/pig/evaluacion_data/ejercicio5/join.out already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:134)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:80)
	... 25 more
================================================================================
